<?xml version="1.0"?>
<robot name="four-wheeled" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="scale" value="1.0" />
    <xacro:property name="caseWidth" value="${0.2032 * scale}" />
    <xacro:property name="caseLength" value="${0.24765 * scale}" />
    <xacro:property name="caseHeight" value="${0.1016 * scale}" />
    <xacro:property name="wheelDiam" value="${0.12065 * scale}" />
    <xacro:property name="wheelWidth" value="${0.05 * scale}"/>
    <xacro:property name="wheelCaseGap" value="${0.0008 * scale}"/>
    <xacro:property name="wheelToMiddleWidth" value="${(caseWidth + wheelWidth)/2 + wheelCaseGap}"/>
    <xacro:property name="wheelToMiddleLength" value="${caseLength/2 - 0.03 * scale}"/>


    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${caseLength} ${caseWidth} ${caseHeight}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <xacro:default_inertial mass="2"/>
        <collision>
            <geometry>
                <box size="${caseLength} ${caseWidth} ${caseHeight}"/>
            </geometry>
        </collision>
    </link>

    <xacro:macro name="wheel" params="prefix suffix origX origY origZ mass">
        <link name="${prefix}_${suffix}_wheel">
            <visual>
                <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelDiam/2}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelDiam/2}"/>
                </geometry>
            </collision>
            <inertial>
                <xacro:property name="r" value="${wheelDiam/2}" />
                <xacro:property name="h" value="${wheelWidth}" />

                <mass value="${mass}" />
                <inertia ixx="${(1/12)*mass*(3*r*r+h*h)}" ixy="0.0" ixz="0.0"
                         iyy="${(1/12)*mass*(3*r*r+h*h)}" iyz="0.0"
                         izz="${0.5*mass*r*r}" />
            </inertial>
        </link>
        <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
            <axis rpy="0 0 0" xyz="0 1 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_${suffix}_wheel"/>
            <origin rpy="0 0 0" xyz="${origX} ${origY} ${origZ}"/>
        </joint>

        <transmission name="${prefix}_${suffix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${prefix}_${suffix}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${prefix}_${suffix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

        <gazebo reference="${prefix}_${suffix}_wheel">
            <mu1 value="200.0"/>
            <mu2 value="100.0"/>
            <kp value="10000000.0" />
            <kd value="1.0" />
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:wheel prefix="rear" suffix="left" origX="${-wheelToMiddleLength}" origY="${wheelToMiddleWidth}" origZ="0.0" mass="0.15"/>
    <xacro:wheel prefix="rear" suffix="right" origX="${-wheelToMiddleLength}" origY="${-wheelToMiddleWidth}" origZ="0.0" mass="0.15"/>
    <xacro:wheel prefix="front" suffix="left" origX="${wheelToMiddleLength}" origY="${wheelToMiddleWidth}" origZ="0.0" mass="0.15"/>
    <xacro:wheel prefix="front" suffix="right" origX="${wheelToMiddleLength}" origY="${-wheelToMiddleWidth}" origZ="0.0" mass="0.15"/>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

</robot>
