#ifndef TOPNAV_SHARED_LIMITS_H
#define TOPNAV_SHARED_LIMITS_H

static const double HOUGH_DEFAULT_MAX_POINT_RANGE = 1.5;
static const double HOKUYO_MAX_AVAILABLE_RANGE_METERS = 5.0;

#endif //TOPNAV_SHARED_LIMITS_H
