<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- head -->
    <link name="head">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${headHeight}" radius="${headDiam/2}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${headHeight}" radius="${headDiam/2}"/>
            </geometry>
        </collision>
        <inertial>
            <xacro:property name="r" value="${headDiam/2}"/>
            <xacro:property name="h" value="${headHeight}"/>

            <!-- TODO solve the problem of the head inertia-->
            <xacro:property name="mass" value="${headWeight * 0.01}"/>

            <mass value="${mass}"/>
            <inertia ixx="${(1/12)*mass*(3*r*r+h*h)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12)*mass*(3*r*r+h*h)}" iyz="0.0"
                     izz="${0.5*mass*r*r}"/>
        </inertial>

    </link>

    <joint name="head_swivel" type="continuous">
        <parent link="base_link"/>
        <child link="head"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${caseLength/2 - headDiam/2} 0 ${caseHeight / 2 + headHeight / 2}"/>
        <limit effort="30" velocity="1.0"/>
        <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <!-- gazebo - head -->
</robot>