<robot>
    <joint name="hokuyo_joint" type="fixed">
        <axis xyz="0 1 0"/>
        <origin xyz="0 0 ${headHeight/2 + hokuyoHeight/2}" rpy="0 0 0"/>
        <parent link="head"/>
        <child link="hokuyo_link"/>
    </joint>

    <!-- Hokuyo Laser -->
    <link name="hokuyo_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${hokuyoSide} ${hokuyoSide} ${hokuyoHeight}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://topnav_bot_description/meshes/hokuyo.dae"/>
            </geometry>
        </visual>

        <inertial>
            <mass value="1e-5"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
        </inertial>
    </link>
</robot>